---
title: Les Petits Hugues
email: valentine@lespetitshugues.fr
description: Le blog des petits bonheurs
baseurl: ''
url: http://lespetitshugues.fr
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    subtitle: ''
    hero_img: ''
    tags: []
    comments: 'true'
markdown: kramdown
gems:
- jekyll-feed
exclude:
- vendor/bundle
- Gemfile
- Gemfile.lock
permalink: "/:categories/:title/"
